import {writeFileSync, readFileSync} from "node:fs"
import pathModule from "node:path"
import process from "node:process"
var json = JSON.parse(readFileSync("package.json"))
var gypDir = json.config.node_gyp_devdir;
var nodeVersion = '/' + process.version.substring(1) + '/'
var paths = {
  NODE_INCLUDE: gypDir + nodeVersion + "include/node",
  NAPI_INCLUDE: "node-addon-api" in json.dependencies || "node-addon-api" in json.devDependencies
    ? "node_modules/node-addon-api"
    : "",
  NODE_LIB: process.platform === "win32"
    ? pathModule.resolve(import.meta.dirname, gypDir + nodeVersion + "x64/node.lib").replaceAll("\\", "/")
    : "",
}
var pathsString = "#Generated by setup-cmake.mjs\n"

for (var pathName in paths) {
  pathsString += `set(${pathName} "${paths[pathName]}")\n`;
}

writeFileSync("paths.cmake", pathsString);
